### PR TITLE
Connect the app to the PostgreSQL database

### PR DESCRIPTION
**Pull request by ErlingHauan**
## Summary

This PR makes it possible for the backend to communicate with the database. Now, when signing up through the frontend, the backend will create a new user entry in the DB. Also, when logging in, we now have to enter an actual user that exists in the DB. 

### Connecting to the database
* Added required NuGet packages to backend.
* Added ConnectionStrings to backend appsettings.json. Different strings for production and development, so that the database is accessible when backend is running in Docker and in development mode.

### New backend classes
* ApiDbContext: Handles configuration to the database.
* SeedData: Contains initial data entries for the database.
* UserRepository: Cointains methods that communicate with the database.
* UserEntity: Datatype that is used between repository and database.

### Yarn commands
* Added command `db:seed` that creates a "Users" table and seeds the database. 
* Added command `yarn start-backend` for easier startup.
* Changed `yarn start-main-app` to `yarn start-frontend`.

### Database GUI
* Added pgAdmin, a database GUI for PostgreSQL. It runs in its own Docker container.

### Tests
* Updated 3/4 tests. The last one will have to wait until we have implemented backend validation for Signup. 
* All tests are currently failing in the pipeline, because they now require the DB to succeed, and the DB does not run in the pipeline.

### Issues that have to be resolved later:
* #88 
* #87 
* #86 
* #85 
* #89

### CODE REVIEW

**Review by mirkoSekulic — CHANGES_REQUESTED** [review]
I'd suggest to create some layers here. 
Too many different stuff is under "Models" directory.
For example you can move EF context to Data directory, repository to Repository etc. Also I'd suggest not to use DTO objects in Repository. Use your "domain" model instead. Conversion between dto and model should be moved to mappers.

**Comment by ErlingHauan** [comment]
Thanks for the feedback 🙂 

The project structure should be improved now.
I have sorted the classes into separate directories, and made the repository use only the UserEntity type instead of UserDto.

How does it look now?

**Review by mirkoSekulic — APPROVED** [review]
LGTM

**Comment by mirkoSekulic** [comment]
The only thing you should fix is the tests. You're trying to connect to the database which is not present in runners.

**Review by mirkoSekulic — CHANGES_REQUESTED** [review]
Tests should be fixed

**Pull request merged**
